### PR TITLE
fix: android bottom covered

### PR DESCRIPTION
**Pull request by wengqianshan**
Snip20221208_1
On some android phones, the bottom will be covered by the popup element

### CODE REVIEW

**Comment by sekizlipenguen** [comment]
Wow! May I know the android version?

Some android phones were having the reverse problem :/

**Comment by wengqianshan** [comment]
Thank you for your reply.
I am reproducing this problem in the android6.0.1 emulator, the reason is that many users reported that the tabbar at the bottom of the application cannot be clicked, and then locate the problem of being covered.

**Comment by wengqianshan** [comment]
Sorry, I forgot the most important point: I use expo-status-bar in my project, it will automatically set the statusbar to translucent in the Android environment, when I specify this component translucent={false}, the bottom covered issues are resolved. But then I lost the top translucency

**Comment by sekizlipenguen** [comment]
Hi,

new update. These new features might work for you. 

import { StatusBar} from 'react-native';
statusBarTranslucent: false or true;
or
```
statusBarTranslucent:true,
onCloseComplete: () => {
    StatusBar. setTranslucent(false);
},
```

```
Toast.show({
      title: 'I\'m Eight!',
      text: 'The best gift I received in this life are the codes. They are worlds inside the worlds.',
      backgroundColor: '#702c91',
      timeColor: '#440f5f',
      timing: 3000,
      icon: <Icon name={'check'} color={'#fff'} size={31}/>,
      position: 'top',
      statusBarTranslucent: false,
      statusBarType:'light-content',
      onCloseComplete: () => {
        alert('onCloseComplete');
      },
      onOpenComplete: () => {
        alert('onOpenComplete');
      },
    });
```

**Pull request closed without merging**
